services:
  app:
    container_name: a7la-app-api
    build: .
    restart: always
    ports:
      - "3965:3000"
    volumes:
      - node_modules:/app/node_modules
      - ../uploads/ijd-a7laApp:/usr/src/app/uploads
volumes:
  node_modules:
